### PR TITLE
Re-fix skin

### PR DESCRIPTION
**Pull request by DelofJ**
Fix the skin on the arm that was wrongly converted
There was an issue when the skin was at the 64x64 format and the Alex type

### CODE REVIEW

**Comment by robinuniverse** [comment]
SKIN ISSUE

**Comment by craftycodie** [comment]
Please provide example skins.

**Comment by DelofJ** [comment]
Provided in https://github.com/craftycodie/MineOnline/issues/332
The fix skin just need to be converted from the 64x64 format to the 32x32 format, and only after need to retexture the arm, this is what the fork do

**Comment by craftycodie** [comment]
I'm happy to merge this but I need skins of all variants for regression testing. Can you provide some?

**Review by craftycodie — APPROVED** [review]

**Review by craftycodie — APPROVED** [review]

**Pull request merged**
